### ISSUE TITLE
Add Version and Platform support in Support Statement section

### ISSUE THREAD

**Issue by troytop** [SUSE/cap-release-notes#81]
The Version and Platform support information found in the internal CAP Support Policy page should be added to the Support Statement section. Here's a paste of the current version:

----------
### Version Support

- Technical Support and Troubleshooting (L1 - L2): Current and previous major versions (N -1). For example: SUSE will provide technical support and troubleshooting for versions 1.0, 1.1, 1.2, 1.3 (and all 2.x point releases) until the release of 3.0.

- Patches and updates (L3): On the latest or last minor release of each major release. For example: SUSE  will provide patches and updates for 1.3 (and 2.latest) until the release of 3.0.

SUSE CAP closely follows upstream Cloud Foundry releases which may implement fixes and
changes which are not backwards compatible with previous releases. SUSE will backport patches
for critical bugs and security issues on a best efforts basis.

### Platform Support

1. CAP is fully supported on Amazon EKS, Azure AKS, and Google GKE. Each release is tested by CAP QA on these platforms.

2. CAP is fully supported on CaaSP, wherever it happens to be installed. If CaaSP is supported on a particular CSP, the customer can get support for CAP in that context. (Note: This has not been tested yet but it is in theory a supportable scenario.)

3. SUSE can provide support for CAP on 3rd party / generic Kubernetes on a case-by-case basis provided:

    a. the Kubernetes cluster satisfies the Requirements listed here:  https://github.com/SUSE/scf/wiki/How-to-Install-SCF#requirements-for-kubernetes
    b. The kube-ready-state-check.sh script has been run on the target Kubernetes cluster and does not show any configuration problems
    c. a SUSE Services or Sales Engineer has verified that CAP works correctly on the target Kubernetes cluster

4. Any incident with SUSE Cloud Application Platform is also fully supported as long as the problem can be replicated on CaaSP, AKS, EKS, or GKE. Bugs identified on 3rd party / generic Kubernetes which are unique to that platform and can not be replicated on the core supported platforms are fixed on a best efforts basis. SUSE will not replicate the deployed Kubernetes environment internally in order to reproduce errors. 
----------

The Kubernetes requirements link should be to the equivalent section of the CAP docs not the scf repo.

**Comment by gaktive** [comment]
Does this need to go in the Docs as well? I'll start incorporating this into a new branch here. 

I wonder if we have to go into any specific K8s versioning requirements, along with additional components like Helm.

**Comment by gaktive** [comment]
@btat do we have anything in our Docs that talk about K8s requirements?

**Comment by gaktive** [comment]
Bah, spoke too soon :) https://documentation.suse.com/suse-cap/1.5.1/html/cap-guides/cha-cap-depl-kube-requirements.html#sec-cap-changes-kube-reqs

**Comment by gaktive** [comment]
PR opened, work to be tracked there.
